name: Deploy to GitHub Pages

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-lastest
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v3
                with:
                    submodules: true
                    fetch-depth: 1

            - uses: actions/setup-node@v3
                with:
                    node-version: [17.x]
                    cache: 'npm'
            
            - run: npm ci
            - run: npm run build --if-present

            - name: Deploy
                uses: peaceiris/actions-gh-pages@v3
                if: ${{ github.ref == 'refs/heads/master' }}
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./dist
